[voting_service]

[voting_service.web]
host = "0.0.0.0"
port = 8080
read_timeout = 10
shutdown_timeout = 5

[voting_service.db]
dbname = "api_db"
host = "localhost"
port = 5432
username = "user"
password = "secret"