[voting_service]

[voting_service.web]
host = "0.0.0.0"
port = 8080
read_timeout = 5
write_timeout = 10
idle_timeout = 60


[voting_service.db]
dbname = "api_db"
host = "localhost"
port = 5432
username = "user"
password = "secret"